name: walkom_mobile_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  auto_route: ^7.4.0
  flutter_osm_plugin: ^0.55.1
  flutter_svg: ^2.0.6
  pinput: ^2.2.31
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  # flutter_map_location_marker: ^6.0.0
  # flutter_map_marker_popup: ^5.1.0
  mapbox_gl: ^0.16.0
  # location: ^5.0.0-dev.8
  yandex_mapkit: ^3.3.2
  # location:
  #   git:
  #     url: https://github.com/781flyingdutchman/flutterlocation.git
  #     ref: 'V4'
  #     path: packages/location
  geolocator: ^9.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/