name: walkom_mobile_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  talker_flutter: ^2.4.3
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  auto_route: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true